### ISSUE TITLE
Feature Request: Unit Test for AppDaemon

### ISSUE THREAD

**Issue by Odianosen25** [nickw444/appdaemon-testing#1]
Hello @nickw444,

Thanks for this framework. I am one of the maintainers for AD, and wanted to ask if there was a way for you to kindly extend your framework to be used to test AD as a whole and not just apps (well I kind of recognise its one and the same thing anyway), nor limited to the `Hass` namespace.

Basically we looking at having a CI/CD pipeline going forward, so every code blocks to be merged can be automatically tested to check for non breaking code before the PR is accepted; mind you this is not something I have done before, so apologies ahead if I missed something. 

Is this something you can help us with please? The target for now will be mostly the general apis, then over time we can expand into specific plugin based apis.

Kind regards

**Comment by nickw444** [comment]
Hi @Odianosen25, the intended scope of this library is to test "apps", rather than appdaemon itself. I don't think there would ever exist a situation where this tool could be "extended" to test base appdaemon (that tooling should live within the appdaemon codebase itself).
